export const actionsEnums = {
    UPDATE_LOADING: 'UPDATE_LOADING ',
    UPDATE_API_RESPONSE: 'UPDATE_API_RESPONSE',
    UPDATE_PASSWORD: 'UPDATE_PASSWORD',
    UPDATE_ACCEPT_CONDITIONS: 'UPDATE_ACCEPT_CONDITIONS',
}